name: Terraform Deploy

on:
  push:
    branches:
      - main # Chạy khi có thay đổi trên nhánh main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Lấy mã nguồn từ GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Bước 2: Cài đặt Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    # Bước 3: Terraform Init
    - name: Terraform Init
      run: terraform init
      working-directory: terraform-vpc

    # Bước 4: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -var "my_ip=118.69.158.111"
      working-directory: terraform-vpc
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
